alias df="df -h"
alias du="du -h"
alias gs="git status"
alias els="exa -lbGF --git --icons --group-directories-first"
alias ell="exa -lbF --git --icons --group-directories-first"
alias elt="exa -lbF --git --icons --group-directories-first --tree --level=2"
alias ela="exa -lbhHgSa@ --git --color-scale --group-directories-first --icons"
alias lg="lazygit"
alias ra="ranger"
alias sl="screenfetch -A 'Arch Linux' | lolcat -F 0.3"
alias sra="sudo -E ranger"
alias sudo="sudo -E"
alias top="glances"
alias vi="nvim"
alias fl="figlet -f slant"
alias tl="tldr"
alias zshrc="nvim $ZDOTDIR/zshrc"

# tmux
alias tmux="tmux -f $HOME/.config/tmux/tmux.conf"
alias tn="tmux new -s"
alias tk="tmux kill-session -t"
alias tka="tmux kill-session -a"
alias tks="tmux kill-server"
alias ta="tmux attach"
alias tat="tmux attach -t"
alias tls="tmux ls"
